subdomain: local
region: local
auth:
  redirection:
    allowedUrls:
      - http://localhost:3000
postgres:
  version: "14"
hasura:
  adminSecret: nhost-admin-secret
  jwtSecrets:
    - type: HS256
      key: nhost-jwt-secret-key-must-be-at-least-32-chars-long
      claims_format: json
functions:
  nodeVersion: "18"
